#!/command/with-contenv sh

[ "${SLEIPNIR_ENABLE_TAILSCALE:-0}" = "1" ] || { s6-svc -O . ; exit 0 ; }

exec s6-setuidgid ubuntu tailscaled \
    --outbound-http-proxy-listen=localhost:1056 \
    --socket=/run/tailscale/tailscaled.sock \
    --socks5-server=localhost:1055 \
    --statedir="${TS_STATE_DIR:-/var/lib/tailscale}" \
    --tun=userspace-networking
